<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BHANU-LAPTOP" failures="2" tests="2" name="TestLocal" time="18.722" errors="0" timestamp="2022-09-23T09:08:42 IST">
  <testcase classname="script.Test1" name="testA" time="1.163">
    <failure type="java.lang.AssertionError" message="expected [CONTACT ME] but found [CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at script.Test1.testA(Test1.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase classname="script.Test2" name="testB" time="0.149">
    <failure type="java.lang.AssertionError" message="expected [CONTACT ME] but found [CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at script.Test2.testB(Test2.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
</testsuite> <!-- TestLocal -->
